version: 2.1

jobs:
  chk_npm_lint_and_test:
    docker:
      - image: cimg/node:current
    resource_class: small
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test

workflows:
  version: 2
  workflow:
    jobs:
      - chk_npm_lint_and_test
